import type { Song } from 'types/model';

export const mockSongList: Array<Song> = [
    {
        id: "123",
        name: "Here We Go Again",
        artist_id: "Person",
        length: 123,
        description: "desc",
        file_uri: "abc",
        num_reviews: 4,
        created_at: 123,
        updated_at: 123,
    },
    {
        id: "123",
        name: "This Time I'm Listening",
        artist_id: "Person",
        length: 398,
        description: "desc",
        file_uri: "abc",
        num_reviews: 2,
        created_at: 123,
        updated_at: 123,
    },
    {
        id: "123",
        name: "This is a Short and Sad Song",
        artist_id: "Person",
        length: 34,
        description: "desc",
        file_uri: "abc",
        num_reviews: 0,
        created_at: 123,
        updated_at: 123,
    },
    {
        id: "123",
        name: "Here We Go Again",
        artist_id: "Person",
        length: 123,
        description: "desc",
        file_uri: "abc",
        num_reviews: 4,
        created_at: 123,
        updated_at: 123,
    },
    {
        id: "123",
        name: "This Time I'm Listening",
        artist_id: "Person",
        length: 398,
        description: "desc",
        file_uri: "abc",
        num_reviews: 2,
        created_at: 123,
        updated_at: 123,
    },
    {
        id: "123",
        name: "This is a Short and Sad Song",
        artist_id: "Person",
        length: 34,
        description: "desc",
        file_uri: "abc",
        num_reviews: 0,
        created_at: 123,
        updated_at: 123,
    },
    {
        id: "123",
        name: "Here We Go Again",
        artist_id: "Person",
        length: 123,
        description: "desc",
        file_uri: "abc",
        num_reviews: 4,
        created_at: 123,
        updated_at: 123,
    },
    {
        id: "123",
        name: "This Time I'm Listening",
        artist_id: "Person",
        length: 398,
        description: "desc",
        file_uri: "abc",
        num_reviews: 2,
        created_at: 123,
        updated_at: 123,
    },
    {
        id: "123",
        name: "This is a Short and Sad Song",
        artist_id: "Person",
        length: 34,
        description: "desc",
        file_uri: "abc",
        num_reviews: 0,
        created_at: 123,
        updated_at: 123,
    },
]